### ISSUE TITLE
unable to see local audio over VPN

### ISSUE THREAD

**Issue by rmarlan** [synfinatic/udp-proxy-2020#103]
Setup - OpenVPN and upd-proxy-2020 on 10.10.10.27 - ubtunu 20.04
Roon Server - on 10.10.10.157 - ubuntu 20.04

After starting the  OpenVPN client and then opening Roon client - the Roon client is able to find the server, but it can not find any of the local client audio devices. The client does see the audio devices on the Server LAN side.  As requested from the roonlabs community site, I have attached the pcap files and included the debug as well.  Any ideas would be appreciated.  I can ping the client from the Roon server and the server from the client with no issues.  I have tried both the macos Roon client and the IOS app and have the same issue with both.  Thanks so much for helping with this!

[pcap.zip](https://github.com/synfinatic/udp-proxy-2020/files/9761293/pcap.zip)

**Comment by synfinatic** [comment]
Honestly, your pcap looks good to me.  Both client and Roon Core are sending Queries and the Core reply is being relayed back to the client.  This should be enough for Roon to discover the TCP ports used for discovering the audio endpoints.  Basically the UDP/9300 traffic is used to bootstrap everything else Roon does- including audio endpoint discovery.  The client makes a connection to the Roon Core to discover the remote endpoints (which you've stated as working) and the Core makes a connection to the client to see what endpoints it has.

You should be able to run `tcpdump -i tun0 -s0 -w roon-vpn.pcap` on your firewall node and then start the Roon app on your phone/laptop.  Let tcpdump run for 15seconds or so (enough time for Roon to start and another 10sec to let discovery do it's thing).

If you inspect the above pcap in [Wireshark](https://www.wireshark.org) you should see your Roon Core making a connection to your phone/laptop- most likely on tcp/9200.

Here is what things look like from my phone named "ComputerInMyPocket" which has an audio endpoint named 'iPhone":
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1075352/195652203-320ea2e8-45da-4e35-85b3-c842fa5a3c82.png">

As you can see, the Core requests the endpoints (red text) and my phone returns its info (blue text).   Based on your earlier pcap, the information about your phone IP and tcp port is getting to the Core, so the most likely cause of this problem is that this connection on tcp/9200 is failing.

If you need help inspecting the pcap above, feel free to attach it here.

One thing to keep in mind... Roon is optimized for working on a high-speed LAN.  Discovery over the VPN can definitely slow things down (even if your VPN is fast).  I've regularly seen discovery of the remote audio endpoint take ~15 seconds.   And occasionally I just have to restart Roon for it to work, my guess is that there is a timing/race condition error in the Roon code which happens when there is added latency on the network.  Sadly, the closed source nature of Roon makes debugging this extremely difficult.

**Comment by rmarlan** [comment]
Hi - Attached is the pcap file generated from tcpdump.  The client is the IOS client brought up over the VPN after starting the tcpdump.  Any thoughts would be appreciated!   Thanks.

[roon-vpn-pcap.pcap.zip](https://github.com/synfinatic/udp-proxy-2020/files/9792929/roon-vpn-pcap.pcap.zip)

**Comment by synfinatic** [comment]
I don't see anything indicating a network issue in that pcap, however I don't see the attempt from the core to talk to your phone to get the audio output devices either.  So that explains why it's not showing up.  Maybe try restarting your Core?

**Comment by synfinatic** [comment]
will be closing this support ticket soon unless I hear more.
